[site]
title = "Jing Wu"
description = "Associate Professor @Tianjin University."
favicon = "/robot.svg"
last_updated = "July 26, 2026"

[author]
name = "Jing Wu"
title = "Associate Professor"
institution = "Tianjin University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "wwujing123@gmail.com"
location = "Tianjin, China"
google_scholar = "https://scholar.google.com.au/citations?user=wRWAmm4AAAAJ&hl=en"
orcid = "https://orcid.org/0009-0004-7049-5480"
github = "https://github.com/JingWu321/"
# linkedin = "https://linkedin.com"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"
